/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#ifdef _MSC_VER
#pragma optimize("", off)
#elif defined(__clang__)
#pragma clang optimize off
#elif defined(__GNUC__)
#pragma GCC optimize ("O0")
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_frontmatter_delimiter = 1,
  aux_sym_directive_if_line_token1 = 2,
  aux_sym_directive_if_line_token2 = 3,
  aux_sym_directive_each_line_token1 = 4,
  aux_sym_directive_each_line_token2 = 5,
  anon_sym_as = 6,
  sym_directive_else_line = 7,
  sym_directive_name_token = 8,
  sym_directive_end_line = 9,
  sym_directive_params = 10,
  sym_comparison_operator = 11,
  sym_logical_operator = 12,
  sym_negation_operator = 13,
  sym_string_literal = 14,
  sym_number_literal = 15,
  sym_boolean_literal = 16,
  sym_heading_marker = 17,
  sym_heading_text = 18,
  sym_code_fence = 19,
  sym_horizontal_rule = 20,
  sym_blank_line = 21,
  sym_text_chunk = 22,
  anon_sym_LBRACE_LBRACE = 23,
  anon_sym_RBRACE_RBRACE = 24,
  anon_sym_LBRACE_LBRACE_LBRACE = 25,
  anon_sym_RBRACE_RBRACE_RBRACE = 26,
  anon_sym_GT = 27,
  aux_sym_partial_ref_token1 = 28,
  anon_sym_PIPE = 29,
  sym_pipe_name = 30,
  sym_path = 31,
  sym_identifier = 32,
  sym_document = 33,
  sym__line = 34,
  sym_directive_if_line = 35,
  sym_directive_each_line = 36,
  sym_directive_named_line = 37,
  sym_condition_expr = 38,
  sym_heading_line = 39,
  sym_content_line = 40,
  sym_expression = 41,
  sym_raw_expression = 42,
  sym_partial_ref = 43,
  sym_expression_body = 44,
  sym_pipe_call = 45,
  sym__pipe_arg = 46,
  aux_sym_document_repeat1 = 47,
  aux_sym_condition_expr_repeat1 = 48,
  aux_sym_heading_line_repeat1 = 49,
  aux_sym_content_line_repeat1 = 50,
  aux_sym_expression_body_repeat1 = 51,
  aux_sym_pipe_call_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_frontmatter_delimiter] = "frontmatter_delimiter",
  [aux_sym_directive_if_line_token1] = "directive_if_prefix",
  [aux_sym_directive_if_line_token2] = "directive_if_line_token2",
  [aux_sym_directive_each_line_token1] = "directive_each_prefix",
  [aux_sym_directive_each_line_token2] = "directive_each_line_token2",
  [anon_sym_as] = "keyword_as",
  [sym_directive_else_line] = "directive_else_line",
  [sym_directive_name_token] = "directive_name_token",
  [sym_directive_end_line] = "directive_end_line",
  [sym_directive_params] = "directive_params",
  [sym_comparison_operator] = "comparison_operator",
  [sym_logical_operator] = "logical_operator",
  [sym_negation_operator] = "negation_operator",
  [sym_string_literal] = "string_literal",
  [sym_number_literal] = "number_literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_heading_marker] = "heading_marker",
  [sym_heading_text] = "heading_text",
  [sym_code_fence] = "code_fence",
  [sym_horizontal_rule] = "horizontal_rule",
  [sym_blank_line] = "blank_line",
  [sym_text_chunk] = "text_chunk",
  [anon_sym_LBRACE_LBRACE] = "expression_open",
  [anon_sym_RBRACE_RBRACE] = "expression_close",
  [anon_sym_LBRACE_LBRACE_LBRACE] = "raw_expression_open",
  [anon_sym_RBRACE_RBRACE_RBRACE] = "raw_expression_close",
  [anon_sym_GT] = "partial_operator",
  [aux_sym_partial_ref_token1] = "partial_ref_token1",
  [anon_sym_PIPE] = "pipe_operator",
  [sym_pipe_name] = "pipe_name",
  [sym_path] = "path",
  [sym_identifier] = "identifier",
  [sym_document] = "document",
  [sym__line] = "_line",
  [sym_directive_if_line] = "directive_if_line",
  [sym_directive_each_line] = "directive_each_line",
  [sym_directive_named_line] = "directive_named_line",
  [sym_condition_expr] = "condition_expr",
  [sym_heading_line] = "heading_line",
  [sym_content_line] = "content_line",
  [sym_expression] = "expression",
  [sym_raw_expression] = "raw_expression",
  [sym_partial_ref] = "partial_ref",
  [sym_expression_body] = "expression_body",
  [sym_pipe_call] = "pipe_call",
  [sym__pipe_arg] = "_pipe_arg",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_condition_expr_repeat1] = "condition_expr_repeat1",
  [aux_sym_heading_line_repeat1] = "heading_line_repeat1",
  [aux_sym_content_line_repeat1] = "content_line_repeat1",
  [aux_sym_expression_body_repeat1] = "expression_body_repeat1",
  [aux_sym_pipe_call_repeat1] = "pipe_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_frontmatter_delimiter] = sym_frontmatter_delimiter,
  [aux_sym_directive_if_line_token1] = aux_sym_directive_if_line_token1,
  [aux_sym_directive_if_line_token2] = aux_sym_directive_if_line_token2,
  [aux_sym_directive_each_line_token1] = aux_sym_directive_each_line_token1,
  [aux_sym_directive_each_line_token2] = aux_sym_directive_each_line_token2,
  [anon_sym_as] = anon_sym_as,
  [sym_directive_else_line] = sym_directive_else_line,
  [sym_directive_name_token] = sym_directive_name_token,
  [sym_directive_end_line] = sym_directive_end_line,
  [sym_directive_params] = sym_directive_params,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_logical_operator] = sym_logical_operator,
  [sym_negation_operator] = sym_negation_operator,
  [sym_string_literal] = sym_string_literal,
  [sym_number_literal] = sym_number_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_heading_marker] = sym_heading_marker,
  [sym_heading_text] = sym_heading_text,
  [sym_code_fence] = sym_code_fence,
  [sym_horizontal_rule] = sym_horizontal_rule,
  [sym_blank_line] = sym_blank_line,
  [sym_text_chunk] = sym_text_chunk,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE_RBRACE,
  [anon_sym_GT] = anon_sym_GT,
  [aux_sym_partial_ref_token1] = aux_sym_partial_ref_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_pipe_name] = sym_pipe_name,
  [sym_path] = sym_path,
  [sym_identifier] = sym_identifier,
  [sym_document] = sym_document,
  [sym__line] = sym__line,
  [sym_directive_if_line] = sym_directive_if_line,
  [sym_directive_each_line] = sym_directive_each_line,
  [sym_directive_named_line] = sym_directive_named_line,
  [sym_condition_expr] = sym_condition_expr,
  [sym_heading_line] = sym_heading_line,
  [sym_content_line] = sym_content_line,
  [sym_expression] = sym_expression,
  [sym_raw_expression] = sym_raw_expression,
  [sym_partial_ref] = sym_partial_ref,
  [sym_expression_body] = sym_expression_body,
  [sym_pipe_call] = sym_pipe_call,
  [sym__pipe_arg] = sym__pipe_arg,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_condition_expr_repeat1] = aux_sym_condition_expr_repeat1,
  [aux_sym_heading_line_repeat1] = aux_sym_heading_line_repeat1,
  [aux_sym_content_line_repeat1] = aux_sym_content_line_repeat1,
  [aux_sym_expression_body_repeat1] = aux_sym_expression_body_repeat1,
  [aux_sym_pipe_call_repeat1] = aux_sym_pipe_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_frontmatter_delimiter] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_directive_if_line_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_directive_if_line_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_each_line_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_directive_each_line_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_else_line] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_name_token] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_end_line] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_params] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_negation_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_text] = {
    .visible = true,
    .named = true,
  },
  [sym_code_fence] = {
    .visible = true,
    .named = true,
  },
  [sym_horizontal_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text_chunk] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE_LBRACE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACE_RBRACE_RBRACE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_partial_ref_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe_name] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_directive_if_line] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_each_line] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_named_line] = {
    .visible = true,
    .named = true,
  },
  [sym_condition_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_line] = {
    .visible = true,
    .named = true,
  },
  [sym_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_partial_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_body] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe_call] = {
    .visible = true,
    .named = true,
  },
  [sym__pipe_arg] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_condition_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipe_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_binding = 2,
  field_collection = 3,
  field_name = 4,
  field_params = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_binding] = "binding",
  [field_collection] = "collection",
  [field_name] = "name",
  [field_params] = "params",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_collection, 1},
  [2] =
    {field_name, 0},
    {field_params, 2},
  [4] =
    {field_name, 2},
  [5] =
    {field_name, 3},
  [6] =
    {field_binding, 5},
    {field_collection, 1},
  [8] =
    {field_arg, 0},
  [9] =
    {field_arg, 4, .inherited = true},
    {field_name, 3},
  [11] =
    {field_arg, 0, .inherited = true},
    {field_arg, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 26,
  [30] = 25,
  [31] = 23,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 37,
  [56] = 44,
  [57] = 57,
  [58] = 51,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_partial_ref_token1);
      if (eof) ADVANCE(198);
      ADVANCE_MAP(
        '\n', 201,
        '!', 214,
        '"', 11,
        '#', 224,
        '-', 14,
        ':', 17,
        '<', 212,
        '=', 18,
        '>', 304,
        '`', 21,
        '{', 185,
        '}', 188,
        '\t', 203,
        ' ', 203,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(216);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 201,
        '!', 214,
        '"', 11,
        '&', 12,
        '<', 212,
        '=', 18,
        '>', 212,
        'f', 311,
        't', 314,
        '|', 187,
        '}', 190,
        '\t', 203,
        ' ', 203,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(216);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(317);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(201);
      if (lookahead == '{') ADVANCE(185);
      if (lookahead != 0) ADVANCE(225);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(201);
      if (lookahead == '{') ADVANCE(186);
      if (lookahead != 0) ADVANCE(298);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(199);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '\n', 209,
        'a', 40,
        'c', 25,
        'e', 26,
        'f', 82,
        'h', 54,
        'i', 73,
        'r', 22,
        '\t', 5,
        ' ', 5,
      );
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(209);
      if (lookahead == 'e') ADVANCE(96);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(226);
      if (lookahead == '{') ADVANCE(8);
      if (lookahead != 0) ADVANCE(232);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(226);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(205);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '>') ADVANCE(303);
      if (lookahead == '|') ADVANCE(308);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(216);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(317);
      END_STATE();
    case 11:
      if (lookahead == '"') ADVANCE(215);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '&') ADVANCE(213);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 14:
      if (lookahead == '-') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == '5') ADVANCE(309);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(6);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == '=') ADVANCE(211);
      END_STATE();
    case 19:
      if (lookahead == '_') ADVANCE(95);
      END_STATE();
    case 20:
      if (lookahead == '`') ADVANCE(8);
      END_STATE();
    case 21:
      if (lookahead == '`') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(180);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(52);
      if (lookahead == 'r') ADVANCE(126);
      END_STATE();
    case 24:
      ADVANCE_MAP(
        'a', 37,
        'c', 27,
        'd', 36,
        'f', 89,
        'j', 131,
        'l', 28,
        'm', 50,
        'n', 172,
        'p', 66,
        'r', 58,
        's', 105,
        't', 80,
        'u', 124,
      );
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(102);
      if (lookahead == 'e') ADVANCE(118);
      if (lookahead == 'o') ADVANCE(97);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(137);
      if (lookahead == 'e') ADVANCE(91);
      if (lookahead == 'o') ADVANCE(178);
      if (lookahead == 'u') ADVANCE(152);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(158);
      if (lookahead == 'o') ADVANCE(181);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(177);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(146);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(160);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(107);
      END_STATE();
    case 35:
      if (lookahead == 'a') ADVANCE(168);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(168);
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead == 'i') ADVANCE(179);
      END_STATE();
    case 37:
      if (lookahead == 'b') ADVANCE(157);
      if (lookahead == 'd') ADVANCE(49);
      if (lookahead == 'p') ADVANCE(136);
      if (lookahead == 's') ADVANCE(204);
      if (lookahead == 't') ADVANCE(309);
      END_STATE();
    case 38:
      if (lookahead == 'b') ADVANCE(170);
      END_STATE();
    case 39:
      if (lookahead == 'b') ADVANCE(68);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(161);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(77);
      END_STATE();
    case 42:
      if (lookahead == 'c') ADVANCE(182);
      END_STATE();
    case 43:
      if (lookahead == 'c') ADVANCE(163);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 46:
      if (lookahead == 'c') ADVANCE(57);
      END_STATE();
    case 47:
      if (lookahead == 'c') ADVANCE(71);
      END_STATE();
    case 48:
      if (lookahead == 'd') ADVANCE(206);
      END_STATE();
    case 49:
      if (lookahead == 'd') ADVANCE(309);
      END_STATE();
    case 50:
      if (lookahead == 'd') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(49);
      if (lookahead == 'u') ADVANCE(110);
      END_STATE();
    case 51:
      if (lookahead == 'd') ADVANCE(156);
      END_STATE();
    case 52:
      if (lookahead == 'd') ADVANCE(61);
      END_STATE();
    case 53:
      if (lookahead == 'd') ADVANCE(57);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 'i') ADVANCE(75);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(149);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(136);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(309);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(139);
      if (lookahead == 'o') ADVANCE(174);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(184);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(142);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(122);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(122);
      if (lookahead == 's') ADVANCE(167);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(144);
      if (lookahead == 'l') ADVANCE(175);
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(123);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(143);
      END_STATE();
    case 69:
      if (lookahead == 'e') ADVANCE(153);
      END_STATE();
    case 70:
      if (lookahead == 'e') ADVANCE(151);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(121);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 73:
      if (lookahead == 'f') ADVANCE(191);
      END_STATE();
    case 74:
      if (lookahead == 'f') ADVANCE(29);
      END_STATE();
    case 75:
      if (lookahead == 'g') ADVANCE(79);
      END_STATE();
    case 76:
      if (lookahead == 'g') ADVANCE(78);
      END_STATE();
    case 77:
      if (lookahead == 'h') ADVANCE(192);
      END_STATE();
    case 78:
      if (lookahead == 'h') ADVANCE(162);
      END_STATE();
    case 79:
      if (lookahead == 'h') ADVANCE(100);
      END_STATE();
    case 80:
      if (lookahead == 'i') ADVANCE(115);
      if (lookahead == 'r') ADVANCE(88);
      END_STATE();
    case 81:
      if (lookahead == 'i') ADVANCE(141);
      END_STATE();
    case 82:
      if (lookahead == 'i') ADVANCE(63);
      if (lookahead == 'o') ADVANCE(135);
      END_STATE();
    case 83:
      if (lookahead == 'i') ADVANCE(183);
      END_STATE();
    case 84:
      if (lookahead == 'i') ADVANCE(127);
      END_STATE();
    case 85:
      if (lookahead == 'i') ADVANCE(140);
      END_STATE();
    case 86:
      if (lookahead == 'i') ADVANCE(163);
      END_STATE();
    case 87:
      if (lookahead == 'i') ADVANCE(117);
      END_STATE();
    case 88:
      if (lookahead == 'i') ADVANCE(112);
      if (lookahead == 'u') ADVANCE(120);
      END_STATE();
    case 89:
      if (lookahead == 'i') ADVANCE(147);
      if (lookahead == 'l') ADVANCE(133);
      if (lookahead == 'r') ADVANCE(129);
      END_STATE();
    case 90:
      if (lookahead == 'i') ADVANCE(165);
      END_STATE();
    case 91:
      if (lookahead == 'i') ADVANCE(98);
      END_STATE();
    case 92:
      if (lookahead == 'i') ADVANCE(76);
      END_STATE();
    case 93:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 94:
      if (lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 95:
      if (lookahead == 'j') ADVANCE(159);
      END_STATE();
    case 96:
      if (lookahead == 'l') ADVANCE(154);
      END_STATE();
    case 97:
      if (lookahead == 'l') ADVANCE(171);
      END_STATE();
    case 98:
      if (lookahead == 'l') ADVANCE(309);
      END_STATE();
    case 99:
      if (lookahead == 'l') ADVANCE(182);
      END_STATE();
    case 100:
      if (lookahead == 'l') ADVANCE(92);
      END_STATE();
    case 101:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 102:
      if (lookahead == 'l') ADVANCE(104);
      END_STATE();
    case 103:
      if (lookahead == 'l') ADVANCE(163);
      END_STATE();
    case 104:
      if (lookahead == 'l') ADVANCE(128);
      END_STATE();
    case 105:
      if (lookahead == 'l') ADVANCE(94);
      if (lookahead == 'o') ADVANCE(146);
      if (lookahead == 'p') ADVANCE(106);
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 106:
      if (lookahead == 'l') ADVANCE(86);
      END_STATE();
    case 107:
      if (lookahead == 'l') ADVANCE(83);
      END_STATE();
    case 108:
      if (lookahead == 'l') ADVANCE(72);
      END_STATE();
    case 109:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 110:
      if (lookahead == 'l') ADVANCE(169);
      END_STATE();
    case 111:
      if (lookahead == 'm') ADVANCE(19);
      END_STATE();
    case 112:
      if (lookahead == 'm') ADVANCE(310);
      END_STATE();
    case 113:
      if (lookahead == 'm') ADVANCE(39);
      END_STATE();
    case 114:
      if (lookahead == 'm') ADVANCE(119);
      END_STATE();
    case 115:
      if (lookahead == 'm') ADVANCE(59);
      if (lookahead == 't') ADVANCE(108);
      END_STATE();
    case 116:
      if (lookahead == 'n') ADVANCE(206);
      END_STATE();
    case 117:
      if (lookahead == 'n') ADVANCE(309);
      END_STATE();
    case 118:
      if (lookahead == 'n') ADVANCE(164);
      END_STATE();
    case 119:
      if (lookahead == 'n') ADVANCE(155);
      END_STATE();
    case 120:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 121:
      if (lookahead == 'n') ADVANCE(163);
      END_STATE();
    case 122:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 123:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 124:
      if (lookahead == 'n') ADVANCE(81);
      if (lookahead == 'p') ADVANCE(138);
      END_STATE();
    case 125:
      if (lookahead == 'n') ADVANCE(57);
      END_STATE();
    case 126:
      if (lookahead == 'o') ADVANCE(206);
      END_STATE();
    case 127:
      if (lookahead == 'o') ADVANCE(116);
      END_STATE();
    case 128:
      if (lookahead == 'o') ADVANCE(173);
      END_STATE();
    case 129:
      if (lookahead == 'o') ADVANCE(111);
      END_STATE();
    case 130:
      if (lookahead == 'o') ADVANCE(117);
      END_STATE();
    case 131:
      if (lookahead == 'o') ADVANCE(87);
      if (lookahead == 's') ADVANCE(130);
      END_STATE();
    case 132:
      if (lookahead == 'o') ADVANCE(125);
      END_STATE();
    case 133:
      if (lookahead == 'o') ADVANCE(134);
      END_STATE();
    case 134:
      if (lookahead == 'o') ADVANCE(143);
      END_STATE();
    case 135:
      if (lookahead == 'o') ADVANCE(166);
      END_STATE();
    case 136:
      if (lookahead == 'p') ADVANCE(64);
      END_STATE();
    case 137:
      if (lookahead == 'p') ADVANCE(90);
      END_STATE();
    case 138:
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 139:
      if (lookahead == 'p') ADVANCE(109);
      if (lookahead == 'v') ADVANCE(70);
      END_STATE();
    case 140:
      if (lookahead == 'p') ADVANCE(99);
      END_STATE();
    case 141:
      if (lookahead == 'q') ADVANCE(176);
      END_STATE();
    case 142:
      if (lookahead == 'r') ADVANCE(206);
      END_STATE();
    case 143:
      if (lookahead == 'r') ADVANCE(309);
      END_STATE();
    case 144:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 145:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 146:
      if (lookahead == 'r') ADVANCE(163);
      END_STATE();
    case 147:
      if (lookahead == 'r') ADVANCE(158);
      END_STATE();
    case 148:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 149:
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 150:
      if (lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 151:
      if (lookahead == 'r') ADVANCE(160);
      END_STATE();
    case 152:
      if (lookahead == 'r') ADVANCE(150);
      END_STATE();
    case 153:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 154:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 155:
      if (lookahead == 's') ADVANCE(206);
      END_STATE();
    case 156:
      if (lookahead == 's') ADVANCE(207);
      END_STATE();
    case 157:
      if (lookahead == 's') ADVANCE(309);
      END_STATE();
    case 158:
      if (lookahead == 's') ADVANCE(163);
      END_STATE();
    case 159:
      if (lookahead == 's') ADVANCE(130);
      END_STATE();
    case 160:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 161:
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 162:
      if (lookahead == 't') ADVANCE(206);
      END_STATE();
    case 163:
      if (lookahead == 't') ADVANCE(309);
      END_STATE();
    case 164:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 165:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 166:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 167:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 168:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 169:
      if (lookahead == 't') ADVANCE(85);
      END_STATE();
    case 170:
      if (lookahead == 't') ADVANCE(148);
      END_STATE();
    case 171:
      if (lookahead == 'u') ADVANCE(114);
      END_STATE();
    case 172:
      if (lookahead == 'u') ADVANCE(113);
      END_STATE();
    case 173:
      if (lookahead == 'u') ADVANCE(162);
      END_STATE();
    case 174:
      if (lookahead == 'u') ADVANCE(122);
      END_STATE();
    case 175:
      if (lookahead == 'u') ADVANCE(145);
      END_STATE();
    case 176:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 177:
      if (lookahead == 'u') ADVANCE(103);
      END_STATE();
    case 178:
      if (lookahead == 'u') ADVANCE(121);
      END_STATE();
    case 179:
      if (lookahead == 'v') ADVANCE(93);
      END_STATE();
    case 180:
      if (lookahead == 'w') ADVANCE(206);
      END_STATE();
    case 181:
      if (lookahead == 'w') ADVANCE(69);
      END_STATE();
    case 182:
      if (lookahead == 'y') ADVANCE(309);
      END_STATE();
    case 183:
      if (lookahead == 'z') ADVANCE(57);
      END_STATE();
    case 184:
      if (lookahead == 'z') ADVANCE(132);
      END_STATE();
    case 185:
      if (lookahead == '{') ADVANCE(299);
      END_STATE();
    case 186:
      if (lookahead == '{') ADVANCE(299);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 187:
      if (lookahead == '|') ADVANCE(213);
      END_STATE();
    case 188:
      if (lookahead == '}') ADVANCE(300);
      END_STATE();
    case 189:
      if (lookahead == '}') ADVANCE(302);
      END_STATE();
    case 190:
      if (lookahead == '}') ADVANCE(189);
      END_STATE();
    case 191:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(200);
      END_STATE();
    case 192:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(202);
      END_STATE();
    case 193:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(217);
      END_STATE();
    case 194:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(318);
      END_STATE();
    case 195:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{') ADVANCE(298);
      END_STATE();
    case 196:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 197:
      if (eof) ADVANCE(198);
      ADVANCE_MAP(
        '\n', 228,
        '#', 224,
        '*', 236,
        '-', 238,
        ':', 241,
        '_', 242,
        '`', 245,
        '{', 186,
        '\t', 234,
        ' ', 234,
      );
      if (lookahead != 0) ADVANCE(298);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_frontmatter_delimiter);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(aux_sym_directive_if_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(200);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(aux_sym_directive_if_line_token2);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(aux_sym_directive_each_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(202);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(aux_sym_directive_each_line_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(203);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_directive_else_line);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_directive_name_token);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_directive_name_token);
      if (lookahead == 'e') ADVANCE(162);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_directive_name_token);
      if (lookahead == 'e') ADVANCE(289);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_directive_end_line);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_directive_params);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_comparison_operator);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_comparison_operator);
      if (lookahead == '=') ADVANCE(211);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_logical_operator);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_negation_operator);
      if (lookahead == '=') ADVANCE(211);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(193);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(216);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(217);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym_boolean_literal);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(317);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(sym_heading_marker);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(219);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(220);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(221);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(222);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(223);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(sym_heading_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{') ADVANCE(225);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(sym_code_fence);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(sym_horizontal_rule);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(sym_blank_line);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '\n') ADVANCE(199);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(229);
      if (lookahead != 0) ADVANCE(298);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(sym_text_chunk);
      ADVANCE_MAP(
        '\n', 209,
        'a', 250,
        'c', 248,
        'e', 249,
        'f', 267,
        'h', 255,
        'i', 261,
        'r', 246,
        '{', 195,
        '\t', 230,
        ' ', 230,
      );
      if (lookahead != 0) ADVANCE(298);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '\n') ADVANCE(209);
      if (lookahead == 'e') ADVANCE(270);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(230);
      if (lookahead != 0) ADVANCE(298);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '\n') ADVANCE(226);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead != 0) ADVANCE(232);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '\n') ADVANCE(205);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(233);
      if (lookahead != 0) ADVANCE(298);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '\n') ADVANCE(228);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(234);
      if (lookahead != 0) ADVANCE(298);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '\n') ADVANCE(227);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(235);
      if (lookahead != 0) ADVANCE(298);
      END_STATE();
    case 236:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '*') ADVANCE(237);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 237:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '*') ADVANCE(235);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 238:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '-') ADVANCE(239);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 239:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '-') ADVANCE(229);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 240:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == ':') ADVANCE(231);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 241:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == ':') ADVANCE(240);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 242:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '_') ADVANCE(243);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 243:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '_') ADVANCE(235);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 244:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '`') ADVANCE(232);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 245:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '`') ADVANCE(244);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 246:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'a') ADVANCE(295);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 247:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'a') ADVANCE(254);
      if (lookahead == 'r') ADVANCE(280);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 248:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'a') ADVANCE(274);
      if (lookahead == 'e') ADVANCE(278);
      if (lookahead == 'o') ADVANCE(271);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 249:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'a') ADVANCE(251);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 250:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'c') ADVANCE(290);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 251:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'c') ADVANCE(264);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 252:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'd') ADVANCE(206);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 253:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'd') ADVANCE(288);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 254:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'd') ADVANCE(257);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 255:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'e') ADVANCE(247);
      if (lookahead == 'i') ADVANCE(262);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 256:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'e') ADVANCE(285);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 257:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'e') ADVANCE(284);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 258:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'e') ADVANCE(252);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 259:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'e') ADVANCE(233);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 260:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'e') ADVANCE(273);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 261:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'f') ADVANCE(296);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 262:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'g') ADVANCE(266);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 263:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'g') ADVANCE(265);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 264:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'h') ADVANCE(297);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 265:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'h') ADVANCE(289);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 266:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'h') ADVANCE(272);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 267:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'i') ADVANCE(260);
      if (lookahead == 'o') ADVANCE(283);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 268:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'i') ADVANCE(281);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 269:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'i') ADVANCE(263);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 270:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'l') ADVANCE(287);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 271:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'l') ADVANCE(293);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 272:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'l') ADVANCE(269);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 273:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'l') ADVANCE(253);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 274:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'l') ADVANCE(275);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 275:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'l') ADVANCE(282);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 276:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'm') ADVANCE(279);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 277:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'n') ADVANCE(206);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 278:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'n') ADVANCE(291);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 279:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'n') ADVANCE(286);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 280:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'o') ADVANCE(206);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 281:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'o') ADVANCE(277);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 282:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'o') ADVANCE(294);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 283:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'o') ADVANCE(292);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 284:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'r') ADVANCE(206);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 285:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'r') ADVANCE(258);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 286:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 's') ADVANCE(206);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 287:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 's') ADVANCE(259);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 288:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 's') ADVANCE(208);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 289:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 't') ADVANCE(206);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 290:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 't') ADVANCE(268);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 291:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 't') ADVANCE(256);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 292:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 't') ADVANCE(257);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 293:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'u') ADVANCE(276);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 294:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'u') ADVANCE(289);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 295:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == 'w') ADVANCE(206);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 296:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(200);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 297:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(202);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 298:
      ACCEPT_TOKEN(sym_text_chunk);
      if (lookahead == '{') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(298);
      END_STATE();
    case 299:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '{') ADVANCE(301);
      END_STATE();
    case 300:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 301:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_LBRACE);
      END_STATE();
    case 302:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE_RBRACE);
      END_STATE();
    case 303:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 304:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(211);
      END_STATE();
    case 305:
      ACCEPT_TOKEN(aux_sym_partial_ref_token1);
      if (lookahead == '}') ADVANCE(188);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(203);
      END_STATE();
    case 306:
      ACCEPT_TOKEN(aux_sym_partial_ref_token1);
      if (lookahead == '}') ADVANCE(188);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(307);
      END_STATE();
    case 307:
      ACCEPT_TOKEN(aux_sym_partial_ref_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(307);
      END_STATE();
    case 308:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 309:
      ACCEPT_TOKEN(sym_pipe_name);
      END_STATE();
    case 310:
      ACCEPT_TOKEN(sym_pipe_name);
      if (lookahead == '_') ADVANCE(65);
      END_STATE();
    case 311:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == 'a') ADVANCE(313);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(317);
      END_STATE();
    case 312:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == 'e') ADVANCE(218);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(317);
      END_STATE();
    case 313:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == 'l') ADVANCE(315);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(317);
      END_STATE();
    case 314:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == 'r') ADVANCE(316);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(317);
      END_STATE();
    case 315:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == 's') ADVANCE(312);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(317);
      END_STATE();
    case 316:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == 'u') ADVANCE(312);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(317);
      END_STATE();
    case 317:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          lookahead == ']' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(317);
      END_STATE();
    case 318:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(318);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 197},
  [2] = {.lex_state = 197},
  [3] = {.lex_state = 197},
  [4] = {.lex_state = 197},
  [5] = {.lex_state = 197},
  [6] = {.lex_state = 197},
  [7] = {.lex_state = 197},
  [8] = {.lex_state = 197},
  [9] = {.lex_state = 197},
  [10] = {.lex_state = 197},
  [11] = {.lex_state = 197},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 305},
  [21] = {.lex_state = 305},
  [22] = {.lex_state = 305},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 306},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 306},
  [28] = {.lex_state = 306},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 305},
  [33] = {.lex_state = 305},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 10},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 306},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 194},
  [46] = {.lex_state = 24},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 196},
  [49] = {.lex_state = 24},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 306},
  [54] = {.lex_state = 194},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 10},
  [58] = {.lex_state = 10},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_frontmatter_delimiter] = ACTIONS(1),
    [aux_sym_directive_if_line_token1] = ACTIONS(1),
    [aux_sym_directive_if_line_token2] = ACTIONS(1),
    [aux_sym_directive_each_line_token1] = ACTIONS(1),
    [aux_sym_directive_each_line_token2] = ACTIONS(1),
    [sym_directive_else_line] = ACTIONS(1),
    [sym_directive_name_token] = ACTIONS(1),
    [sym_directive_end_line] = ACTIONS(1),
    [sym_comparison_operator] = ACTIONS(1),
    [sym_negation_operator] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_heading_marker] = ACTIONS(1),
    [sym_code_fence] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [aux_sym_partial_ref_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(52),
    [sym__line] = STATE(3),
    [sym_directive_if_line] = STATE(3),
    [sym_directive_each_line] = STATE(3),
    [sym_directive_named_line] = STATE(3),
    [sym_heading_line] = STATE(3),
    [sym_content_line] = STATE(3),
    [sym_expression] = STATE(15),
    [sym_raw_expression] = STATE(15),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_content_line_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_frontmatter_delimiter] = ACTIONS(5),
    [aux_sym_directive_if_line_token1] = ACTIONS(7),
    [aux_sym_directive_each_line_token1] = ACTIONS(9),
    [sym_directive_else_line] = ACTIONS(5),
    [sym_directive_name_token] = ACTIONS(11),
    [sym_directive_end_line] = ACTIONS(5),
    [sym_heading_marker] = ACTIONS(13),
    [sym_code_fence] = ACTIONS(5),
    [sym_horizontal_rule] = ACTIONS(15),
    [sym_blank_line] = ACTIONS(5),
    [sym_text_chunk] = ACTIONS(17),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(19),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(28), 1,
      aux_sym_directive_if_line_token1,
    ACTIONS(31), 1,
      aux_sym_directive_each_line_token1,
    ACTIONS(34), 1,
      sym_directive_name_token,
    ACTIONS(37), 1,
      sym_heading_marker,
    ACTIONS(40), 1,
      sym_horizontal_rule,
    ACTIONS(43), 1,
      sym_text_chunk,
    ACTIONS(46), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(49), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    STATE(15), 3,
      sym_expression,
      sym_raw_expression,
      aux_sym_content_line_repeat1,
    ACTIONS(25), 5,
      sym_frontmatter_delimiter,
      sym_directive_else_line,
      sym_directive_end_line,
      sym_code_fence,
      sym_blank_line,
    STATE(2), 7,
      sym__line,
      sym_directive_if_line,
      sym_directive_each_line,
      sym_directive_named_line,
      sym_heading_line,
      sym_content_line,
      aux_sym_document_repeat1,
  [49] = 12,
    ACTIONS(7), 1,
      aux_sym_directive_if_line_token1,
    ACTIONS(9), 1,
      aux_sym_directive_each_line_token1,
    ACTIONS(11), 1,
      sym_directive_name_token,
    ACTIONS(13), 1,
      sym_heading_marker,
    ACTIONS(17), 1,
      sym_text_chunk,
    ACTIONS(19), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      sym_horizontal_rule,
    STATE(15), 3,
      sym_expression,
      sym_raw_expression,
      aux_sym_content_line_repeat1,
    ACTIONS(54), 5,
      sym_frontmatter_delimiter,
      sym_directive_else_line,
      sym_directive_end_line,
      sym_code_fence,
      sym_blank_line,
    STATE(2), 7,
      sym__line,
      sym_directive_if_line,
      sym_directive_each_line,
      sym_directive_named_line,
      sym_heading_line,
      sym_content_line,
      aux_sym_document_repeat1,
  [98] = 2,
    ACTIONS(60), 3,
      sym_horizontal_rule,
      sym_text_chunk,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(58), 11,
      ts_builtin_sym_end,
      sym_frontmatter_delimiter,
      aux_sym_directive_if_line_token1,
      aux_sym_directive_each_line_token1,
      sym_directive_else_line,
      sym_directive_name_token,
      sym_directive_end_line,
      sym_heading_marker,
      sym_code_fence,
      sym_blank_line,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [117] = 2,
    ACTIONS(64), 3,
      sym_horizontal_rule,
      sym_text_chunk,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(62), 11,
      ts_builtin_sym_end,
      sym_frontmatter_delimiter,
      aux_sym_directive_if_line_token1,
      aux_sym_directive_each_line_token1,
      sym_directive_else_line,
      sym_directive_name_token,
      sym_directive_end_line,
      sym_heading_marker,
      sym_code_fence,
      sym_blank_line,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [136] = 2,
    ACTIONS(68), 3,
      sym_horizontal_rule,
      sym_text_chunk,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(66), 11,
      ts_builtin_sym_end,
      sym_frontmatter_delimiter,
      aux_sym_directive_if_line_token1,
      aux_sym_directive_each_line_token1,
      sym_directive_else_line,
      sym_directive_name_token,
      sym_directive_end_line,
      sym_heading_marker,
      sym_code_fence,
      sym_blank_line,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [155] = 2,
    ACTIONS(72), 3,
      sym_horizontal_rule,
      sym_text_chunk,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(70), 11,
      ts_builtin_sym_end,
      sym_frontmatter_delimiter,
      aux_sym_directive_if_line_token1,
      aux_sym_directive_each_line_token1,
      sym_directive_else_line,
      sym_directive_name_token,
      sym_directive_end_line,
      sym_heading_marker,
      sym_code_fence,
      sym_blank_line,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [174] = 2,
    ACTIONS(76), 3,
      sym_horizontal_rule,
      sym_text_chunk,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(74), 11,
      ts_builtin_sym_end,
      sym_frontmatter_delimiter,
      aux_sym_directive_if_line_token1,
      aux_sym_directive_each_line_token1,
      sym_directive_else_line,
      sym_directive_name_token,
      sym_directive_end_line,
      sym_heading_marker,
      sym_code_fence,
      sym_blank_line,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [193] = 2,
    ACTIONS(80), 3,
      sym_horizontal_rule,
      sym_text_chunk,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(78), 11,
      ts_builtin_sym_end,
      sym_frontmatter_delimiter,
      aux_sym_directive_if_line_token1,
      aux_sym_directive_each_line_token1,
      sym_directive_else_line,
      sym_directive_name_token,
      sym_directive_end_line,
      sym_heading_marker,
      sym_code_fence,
      sym_blank_line,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [212] = 2,
    ACTIONS(84), 3,
      sym_horizontal_rule,
      sym_text_chunk,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(82), 11,
      ts_builtin_sym_end,
      sym_frontmatter_delimiter,
      aux_sym_directive_if_line_token1,
      aux_sym_directive_each_line_token1,
      sym_directive_else_line,
      sym_directive_name_token,
      sym_directive_end_line,
      sym_heading_marker,
      sym_code_fence,
      sym_blank_line,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [231] = 2,
    ACTIONS(88), 3,
      sym_horizontal_rule,
      sym_text_chunk,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(86), 11,
      ts_builtin_sym_end,
      sym_frontmatter_delimiter,
      aux_sym_directive_if_line_token1,
      aux_sym_directive_each_line_token1,
      sym_directive_else_line,
      sym_directive_name_token,
      sym_directive_end_line,
      sym_heading_marker,
      sym_code_fence,
      sym_blank_line,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [250] = 4,
    STATE(13), 1,
      aux_sym_condition_expr_repeat1,
    STATE(40), 1,
      sym_condition_expr,
    ACTIONS(92), 3,
      sym_negation_operator,
      sym_boolean_literal,
      sym_path,
    ACTIONS(90), 5,
      aux_sym_directive_each_line_token2,
      sym_comparison_operator,
      sym_logical_operator,
      sym_string_literal,
      sym_number_literal,
  [269] = 4,
    ACTIONS(94), 1,
      aux_sym_directive_if_line_token2,
    STATE(14), 1,
      aux_sym_condition_expr_repeat1,
    ACTIONS(98), 3,
      sym_negation_operator,
      sym_boolean_literal,
      sym_path,
    ACTIONS(96), 5,
      aux_sym_directive_each_line_token2,
      sym_comparison_operator,
      sym_logical_operator,
      sym_string_literal,
      sym_number_literal,
  [288] = 4,
    ACTIONS(100), 1,
      aux_sym_directive_if_line_token2,
    STATE(14), 1,
      aux_sym_condition_expr_repeat1,
    ACTIONS(105), 3,
      sym_negation_operator,
      sym_boolean_literal,
      sym_path,
    ACTIONS(102), 5,
      aux_sym_directive_each_line_token2,
      sym_comparison_operator,
      sym_logical_operator,
      sym_string_literal,
      sym_number_literal,
  [307] = 5,
    ACTIONS(19), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    ACTIONS(108), 1,
      aux_sym_directive_if_line_token2,
    ACTIONS(110), 1,
      sym_text_chunk,
    STATE(16), 3,
      sym_expression,
      sym_raw_expression,
      aux_sym_content_line_repeat1,
  [325] = 5,
    ACTIONS(112), 1,
      aux_sym_directive_if_line_token2,
    ACTIONS(114), 1,
      sym_text_chunk,
    ACTIONS(117), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(120), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    STATE(16), 3,
      sym_expression,
      sym_raw_expression,
      aux_sym_content_line_repeat1,
  [343] = 5,
    ACTIONS(123), 1,
      aux_sym_directive_if_line_token2,
    ACTIONS(125), 1,
      sym_heading_text,
    ACTIONS(127), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(129), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    STATE(19), 3,
      sym_expression,
      sym_raw_expression,
      aux_sym_heading_line_repeat1,
  [361] = 5,
    ACTIONS(131), 1,
      aux_sym_directive_if_line_token2,
    ACTIONS(133), 1,
      sym_heading_text,
    ACTIONS(136), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(139), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    STATE(18), 3,
      sym_expression,
      sym_raw_expression,
      aux_sym_heading_line_repeat1,
  [379] = 5,
    ACTIONS(127), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(129), 1,
      anon_sym_LBRACE_LBRACE_LBRACE,
    ACTIONS(142), 1,
      aux_sym_directive_if_line_token2,
    ACTIONS(144), 1,
      sym_heading_text,
    STATE(18), 3,
      sym_expression,
      sym_raw_expression,
      aux_sym_heading_line_repeat1,
  [397] = 5,
    ACTIONS(146), 1,
      aux_sym_directive_each_line_token2,
    ACTIONS(149), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(151), 1,
      aux_sym_partial_ref_token1,
    STATE(20), 1,
      aux_sym_pipe_call_repeat1,
    STATE(32), 1,
      sym__pipe_arg,
  [413] = 5,
    ACTIONS(153), 1,
      aux_sym_directive_each_line_token2,
    ACTIONS(155), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(157), 1,
      aux_sym_partial_ref_token1,
    STATE(22), 1,
      aux_sym_pipe_call_repeat1,
    STATE(32), 1,
      sym__pipe_arg,
  [429] = 5,
    ACTIONS(153), 1,
      aux_sym_directive_each_line_token2,
    ACTIONS(159), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(161), 1,
      aux_sym_partial_ref_token1,
    STATE(20), 1,
      aux_sym_pipe_call_repeat1,
    STATE(32), 1,
      sym__pipe_arg,
  [445] = 3,
    ACTIONS(163), 1,
      anon_sym_GT,
    ACTIONS(165), 1,
      sym_path,
    STATE(37), 2,
      sym_partial_ref,
      sym_expression_body,
  [456] = 3,
    ACTIONS(167), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(169), 1,
      aux_sym_partial_ref_token1,
    STATE(28), 2,
      sym_pipe_call,
      aux_sym_expression_body_repeat1,
  [467] = 2,
    ACTIONS(173), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(171), 3,
      aux_sym_directive_if_line_token2,
      sym_text_chunk,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [476] = 2,
    ACTIONS(177), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(175), 3,
      aux_sym_directive_if_line_token2,
      sym_text_chunk,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [485] = 3,
    ACTIONS(179), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(181), 1,
      aux_sym_partial_ref_token1,
    STATE(27), 2,
      sym_pipe_call,
      aux_sym_expression_body_repeat1,
  [496] = 3,
    ACTIONS(169), 1,
      aux_sym_partial_ref_token1,
    ACTIONS(184), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(27), 2,
      sym_pipe_call,
      aux_sym_expression_body_repeat1,
  [507] = 2,
    ACTIONS(177), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(175), 3,
      aux_sym_directive_if_line_token2,
      sym_heading_text,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [516] = 2,
    ACTIONS(173), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(171), 3,
      aux_sym_directive_if_line_token2,
      sym_heading_text,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [525] = 3,
    ACTIONS(163), 1,
      anon_sym_GT,
    ACTIONS(165), 1,
      sym_path,
    STATE(55), 2,
      sym_partial_ref,
      sym_expression_body,
  [536] = 2,
    ACTIONS(188), 1,
      aux_sym_partial_ref_token1,
    ACTIONS(186), 2,
      aux_sym_directive_each_line_token2,
      anon_sym_RBRACE_RBRACE,
  [544] = 2,
    ACTIONS(192), 1,
      aux_sym_partial_ref_token1,
    ACTIONS(190), 2,
      aux_sym_directive_each_line_token2,
      anon_sym_RBRACE_RBRACE,
  [552] = 1,
    ACTIONS(194), 3,
      sym_string_literal,
      sym_number_literal,
      sym_path,
  [558] = 2,
    ACTIONS(196), 1,
      aux_sym_directive_if_line_token2,
    ACTIONS(198), 1,
      aux_sym_directive_each_line_token2,
  [565] = 2,
    ACTIONS(200), 1,
      aux_sym_directive_if_line_token2,
    ACTIONS(202), 1,
      aux_sym_directive_each_line_token2,
  [572] = 1,
    ACTIONS(204), 1,
      anon_sym_RBRACE_RBRACE,
  [576] = 1,
    ACTIONS(206), 1,
      aux_sym_directive_each_line_token2,
  [580] = 1,
    ACTIONS(208), 1,
      aux_sym_directive_each_line_token2,
  [584] = 1,
    ACTIONS(210), 1,
      aux_sym_directive_if_line_token2,
  [588] = 1,
    ACTIONS(212), 1,
      sym_path,
  [592] = 1,
    ACTIONS(214), 1,
      anon_sym_RBRACE_RBRACE,
  [596] = 1,
    ACTIONS(216), 1,
      aux_sym_partial_ref_token1,
  [600] = 1,
    ACTIONS(218), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [604] = 1,
    ACTIONS(220), 1,
      sym_identifier,
  [608] = 1,
    ACTIONS(222), 1,
      sym_pipe_name,
  [612] = 1,
    ACTIONS(224), 1,
      aux_sym_directive_if_line_token2,
  [616] = 1,
    ACTIONS(226), 1,
      sym_directive_params,
  [620] = 1,
    ACTIONS(228), 1,
      anon_sym_as,
  [624] = 1,
    ACTIONS(230), 1,
      aux_sym_directive_if_line_token2,
  [628] = 1,
    ACTIONS(232), 1,
      sym_path,
  [632] = 1,
    ACTIONS(234), 1,
      ts_builtin_sym_end,
  [636] = 1,
    ACTIONS(236), 1,
      aux_sym_partial_ref_token1,
  [640] = 1,
    ACTIONS(238), 1,
      sym_identifier,
  [644] = 1,
    ACTIONS(240), 1,
      anon_sym_RBRACE_RBRACE,
  [648] = 1,
    ACTIONS(242), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [652] = 1,
    ACTIONS(244), 1,
      anon_sym_PIPE,
  [656] = 1,
    ACTIONS(246), 1,
      sym_path,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 117,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 155,
  [SMALL_STATE(8)] = 174,
  [SMALL_STATE(9)] = 193,
  [SMALL_STATE(10)] = 212,
  [SMALL_STATE(11)] = 231,
  [SMALL_STATE(12)] = 250,
  [SMALL_STATE(13)] = 269,
  [SMALL_STATE(14)] = 288,
  [SMALL_STATE(15)] = 307,
  [SMALL_STATE(16)] = 325,
  [SMALL_STATE(17)] = 343,
  [SMALL_STATE(18)] = 361,
  [SMALL_STATE(19)] = 379,
  [SMALL_STATE(20)] = 397,
  [SMALL_STATE(21)] = 413,
  [SMALL_STATE(22)] = 429,
  [SMALL_STATE(23)] = 445,
  [SMALL_STATE(24)] = 456,
  [SMALL_STATE(25)] = 467,
  [SMALL_STATE(26)] = 476,
  [SMALL_STATE(27)] = 485,
  [SMALL_STATE(28)] = 496,
  [SMALL_STATE(29)] = 507,
  [SMALL_STATE(30)] = 516,
  [SMALL_STATE(31)] = 525,
  [SMALL_STATE(32)] = 536,
  [SMALL_STATE(33)] = 544,
  [SMALL_STATE(34)] = 552,
  [SMALL_STATE(35)] = 558,
  [SMALL_STATE(36)] = 565,
  [SMALL_STATE(37)] = 572,
  [SMALL_STATE(38)] = 576,
  [SMALL_STATE(39)] = 580,
  [SMALL_STATE(40)] = 584,
  [SMALL_STATE(41)] = 588,
  [SMALL_STATE(42)] = 592,
  [SMALL_STATE(43)] = 596,
  [SMALL_STATE(44)] = 600,
  [SMALL_STATE(45)] = 604,
  [SMALL_STATE(46)] = 608,
  [SMALL_STATE(47)] = 612,
  [SMALL_STATE(48)] = 616,
  [SMALL_STATE(49)] = 620,
  [SMALL_STATE(50)] = 624,
  [SMALL_STATE(51)] = 628,
  [SMALL_STATE(52)] = 632,
  [SMALL_STATE(53)] = 636,
  [SMALL_STATE(54)] = 640,
  [SMALL_STATE(55)] = 644,
  [SMALL_STATE(56)] = 648,
  [SMALL_STATE(57)] = 652,
  [SMALL_STATE(58)] = 656,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_line, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_line, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_named_line, 2, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_named_line, 2, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_if_line, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_if_line, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_each_line, 3, 0, 2),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_each_line, 3, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_line, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading_line, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_named_line, 4, 0, 3),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_named_line, 4, 0, 3),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_each_line, 7, 0, 6),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_each_line, 7, 0, 6),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_line, 4, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading_line, 4, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition_expr, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_condition_expr_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_condition_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_condition_expr_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_line_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_line_repeat1, 2, 0, 0),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_line_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_line_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_line_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipe_call_repeat1, 2, 0, 9), SHIFT_REPEAT(34),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipe_call_repeat1, 2, 0, 9),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pipe_call_repeat1, 2, 0, 9),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_call, 4, 0, 5),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_call, 4, 0, 5),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_call, 5, 0, 8),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_call, 5, 0, 8),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_body, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_expression, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_expression, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_body_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_body_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_body, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipe_call_repeat1, 1, 0, 7),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pipe_call_repeat1, 1, 0, 7),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pipe_arg, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__pipe_arg, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partial_ref, 3, 0, 4),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [234] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_norq(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
